apiVersion: apps/v1
kind: Deployment-Pod
metadata: 
 name: nginx-Deployment
 labels:
  type: proxyserver
  author: intelliqit
spec: 
 replicas: 3
 selector:
  matchLabels:
   type: proxyserver
 template:
  metadata:
   name: nginx-Pod
   labels:
    type: proxyserver
  spec:
   containers:
    - name: nginx
      image: nginx:1.7.9
      ports: 
       - containerPorts: 80
         HostPort: 8989