---
apiVersion: v1
kind: Pod
metadata:
 name: jenkins-Pod
 labels:
  type: ci-cd
  author: intelliqit
spec:
 containers:
  - name: jenkins
    image: jenkins
    ports:
     - containerPorts: 8080
       HostPort: 8080